name: ProfaneAndSacred
favicon: null
layout_spectrum: 0.91452
typography_spectrum: 0.79851
title: Profane and Sacred
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5625
  lightness: 0.4499713263940066
  saturation: 0.625
  rhythmicContrast: 0.4962277659215033
purpose: []
